In [3]:
#libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [4]:
dataset = pd.read_csv('IRIS.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

In [5]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
dataset.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [18]:
#spliting data into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [32]:
#labeling because Y is categorical
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
Label = LabelEncoder()
Y_train = Label.fit_transform(Y_train)
Y_test = Label.transform(Y_test)

In [20]:
#Naive bayes 
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [27]:
y_predict = nb.predict(X_test)

In [28]:
y_predict

array([2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 1, 2, 2, 1, 2, 1, 0, 2, 2,
       1, 0, 0, 1, 2, 2, 1, 0])

In [29]:
Y_test

array([2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 1, 0, 2, 2,
       1, 0, 0, 1, 2, 2, 1, 0])

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
conf_matrix = confusion_matrix(Y_test,y_predict)
conf_matrix

array([[12,  0,  0],
       [ 0,  6,  0],
       [ 0,  1, 11]], dtype=int64)

In [31]:
accuracy_score(Y_test,y_predict)

0.9666666666666667

In [33]:
def irisModel(petal_width,petal_length):
    
    petal_width = float(petal_width)
    petal_length = float(petal_length)
    
    if petal_width >=0.1 and petal_width <=0.7:
        if petal_length >=0.8 and petal_length <= 2.0:
            print("Flower is identified to be SETOSA")
            
            
    elif petal_width >=0.9 and petal_width <=1.6:
        if petal_length >=3.0 and petal_length <= 4.8:
            print("Flower is identified to be VERSICOLOR")
            
            
    elif petal_width >=1.7 and petal_width <=2.6:
        if petal_length >=4.9 and petal_length <= 7.0:
            print("Flower is identified to be VIRGINICA")
            
            
    else:
        print("Flower Doesnot belong to Iris family")

In [34]:
irisModel(1.2, 4.5)

Flower is identified to be VERSICOLOR
